### PR TITLE
Update Aspsms.php

### PR DESCRIPTION
**Pull request by sgry**
Quick and dirty Fix to be able to send unicode messages

### CODE REVIEW

**Comment by nadar** [comment]
So the only diff is to use new endpoint `SendUnicodeSMS` instead of `SendTextSMS`?

**Comment by sgry** [comment]
Yes. I was too lazy to deduplicate the code. Let me make it better.

**Comment by nadar** [comment]
looks good, thanks. i will add the phpdoc version information and changelogs and release afterwards. thanks for your PR, i appreciate that

**Comment by sgry** [comment]
Perfect, thanks a lot :)

**Comment by nadar** [comment]
https://github.com/nadar/aspsms/releases/tag/1.1.0

**Pull request merged**
